### ISSUE TITLE
[BUG] - "synchronize" event seems not enough

### ISSUE THREAD

**Issue by yoanmLf** [yoanm/github-action-deps-versions-checker#55]
**Describe the bug**
Using only `synchronize` event avoid triggering the action when PR is just "opened"

**To Reproduce**
Open a PR, action will not be triggered, it will only if another commit is pushed to the branch

**Expected behavior**
Action triggered when PR is opened or updated

**Screenshots**

**Additional context**

Adding `opened` along with `synchronize` should fix the issue (`reopened` doesn't seems useful in current case)

**Comment by yoanm** [comment]
See acbe2dc
